version: '3'

services:
  db:
   container_name: dj-mysql
   image: mysql/mysql-server:5.7
   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   environment:
    MYSQL_DATABASE: dj
    MYSQL_ROOT_PASSWORD: dj1234
    MYSQL_ROOT_HOST: '%'
   ports:
   - "127.0.0.1:3307:3306"
#   volumes:
#    - /opt/docker-volumes/dj/mysql:/var/lib/mysql
   restart: always
  web:
    container_name: dj-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db